#CXXFLAGS=-lqpidcommon -lqpidmessaging -O2 -g -L ~/mrg-qpid/build/src/.libs -I ~/mrg-qpid/qpid/cpp/include
#CXXFLAGS=-lqpidcommon -lqpidmessaging -O2 -g #-L ~/mrg-qpid/build/src/.libs -I ~/mrg-qpid/qpid/cpp/include
CXXFLAGS=-lqpidcommon -lqpidmessaging -O2 -g -I/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/include -I/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/include/linux -I/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre/lib/amd64/server -L/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre/lib/amd64/server -ljvm


all: jdgconsume
